# For time being, used the hard coded hostname and container name in the docker-comose file
# later, we need to work on it to bring these names from the environment files. 
#
version: '3'
services:
  docker_ntierdemo_app:    
    image: marimuthups/dockerntierdemo_app:v2
    build:
      context: ./NtierMvc/bin/Release/Publish          
    depends_on:
      - docker_ntierdemo_db
    #hostname: ${APP_UUID}
    #container_name: ${APP_UUID}
    hostname: Demo_App_Server
    container_name: Demo_App_Server
    networks: 
      docker_ntierdemo-net:        
        ipv4_address: 172.16.238.20         
  docker_ntierdemo_db:
    image: marimuthups/dockerntierdemo_db:v1   
    build:      
      context: ./Database 
    ports: 
      - "14333:1433"
    env_file: db_dev.env   
    #hostname: ${DB_UUID}
    #container_name: ${DB_UUID}    
    hostname: Demo_Db_Server
    container_name: Demo_Db_Server
    networks: 
      docker_ntierdemo-net:             
        ipv4_address: 172.16.238.21
networks:
  docker_ntierdemo-net:       
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
